##############################
# litechat API Configuration #
##############################

[default]
# The port to use. Both WS and REST use the same port.
port = 6910
# The current API version.
version = 1
# Logging level. (debug | trace | info | warn | error | fatal)
log_level = "debug"
# Will send logs to a discord webhook if provided
log_webhook = false

[prod]
port = 6910

[dev]
port = 6911